"""Monthly payment calculation."""

import decimal
from decimal import Decimal

from mortgagemath._types import DayCount, LoanParams, PaymentRounding

_PENNY = Decimal("0.01")

_ROUNDING_MAP = {
    PaymentRounding.ROUND_UP: decimal.ROUND_UP,
    PaymentRounding.ROUND_HALF_UP: decimal.ROUND_HALF_UP,
    PaymentRounding.ROUND_HALF_EVEN: decimal.ROUND_HALF_EVEN,
}


def monthly_payment(loan: LoanParams) -> Decimal:
    """Calculate the monthly principal and interest payment for a loan.

    Uses the standard annuity formula with Decimal arithmetic throughout::

        r = annual_rate / 1200
        payment = P * r * (1+r)^n / ((1+r)^n - 1)

    The result is rounded according to ``loan.payment_rounding``.

    The same closed-form formula applies to both 30/360 and Actual/360 loans:
    the convention determines how the schedule accrues interest each period,
    not how the level monthly payment is computed. This matches the Fannie Mae
    Multifamily Selling and Servicing Guide §1103, where the "calculated
    actual/360 fixed rate payment" is the standard annuity value (validated
    against the §1103 worked example: $25M / 5.5% / 30yr → DSC 6.8134680%
    → monthly P&I $141,947.25).

    For ACTUAL_360 the schedule itself (each month's interest based on
    actual calendar days × rate / 360) is not yet generated by this
    library; see ``docs/future-work.md``.

    Args:
        loan: Loan parameters.

    Returns:
        Monthly P&I payment rounded to the nearest cent.

    Raises:
        ValueError: If principal or term_months is not positive, or the
            day_count is unsupported.
    """
    if loan.principal <= 0:
        raise ValueError(f"principal must be positive, got {loan.principal}")
    if loan.term_months <= 0:
        raise ValueError(f"term_months must be positive, got {loan.term_months}")
    if loan.day_count not in (DayCount.THIRTY_360, DayCount.ACTUAL_360):
        raise ValueError(f"unsupported day_count: {loan.day_count}")

    rounding = _ROUNDING_MAP[loan.payment_rounding]
    r = loan.annual_rate / Decimal("1200")
    n = loan.term_months
    payment = loan.principal * r * (1 + r) ** n / ((1 + r) ** n - 1)

    return payment.quantize(_PENNY, rounding=rounding)
