blank_issues_enabled: false
contact_links:
  - name: Question or open-ended discussion
    url: https://github.com/murraystokely/mortgagemath/discussions
    about: For questions or open-ended discussion, please use Discussions rather than Issues.
